### ISSUE TITLE
getVersion 报错

### ISSUE THREAD

**Issue by popomore** [spmjs/spm-client#31]
在安装过程中，getVersion 去获取依赖模块的 package.json 可能不存在

https://github.com/popomore/father/blob/0.10.6/lib/util.js#L46

```
        install: seajs@2.2.1
$CWD/spm_modules/seajs/2.2.1/package.json
true
          found: seajs@2.2.1
        install: seajs-text@1.1.0
$CWD/spm_modules/seajs-text/1.1.0/package.json
true
          found: seajs-text@1.1.0
        install: seajs-style@1.1.0
$CWD/spm_modules/seajs-style/1.1.0/package.json
true
          found: seajs-style@1.1.0
        install: jquery@1.7.2
$CWD/spm_modules/jquery/1.7.2/package.json
true
          found: jquery@1.7.2
        install: handlebars@1.3.0
        install: import-style@1.0.0
$CWD/spm_modules/import-style/1.0.0/package.json
true
          found: import-style@1.0.0
        install: swfobject@2.2.0
$CWD/spm_modules/swfobject/2.2.0/package.json
true
          found: swfobject@2.2.0
        install: json@0.0.2
$CWD/spm_modules/json/0.0.2/package.json
true
          found: json@0.0.2
        install: underscore@1.6.0
$CWD/spm_modules/underscore/1.6.0/package.json
false
        install: moment@2.6.0
        install: handlebars-runtime@1.3.0
$CWD/spm_modules/handlebars-runtime/1.3.0/package.json
false
        install: arale-base@1.2.0
```

**Comment by nnakornn** [comment]
> 在安装过程中，getVersion 去获取依赖模块的 package.json 可能不存在
> 
> https://github.com/popomore/father/blob/0.10.6/lib/util.js#L46
> 
> ```
>         install: seajs@2.2.1
> $CWD/spm_modules/seajs/2.2.1/package.json
> true
>           found: seajs@2.2.1
>         install: seajs-text@1.1.0
> $CWD/spm_modules/seajs-text/1.1.0/package.json
> true
>           found: seajs-text@1.1.0
>         install: seajs-style@1.1.0
> $CWD/spm_modules/seajs-style/1.1.0/package.json
> true
>           found: seajs-style@1.1.0
>         install: jquery@1.7.2
> $CWD/spm_modules/jquery/1.7.2/package.json
> true
>           found: jquery@1.7.2
>         install: handlebars@1.3.0
>         install: import-style@1.0.0
> $CWD/spm_modules/import-style/1.0.0/package.json
> true
>           found: import-style@1.0.0
>         install: swfobject@2.2.0
> $CWD/spm_modules/swfobject/2.2.0/package.json
> true
>           found: swfobject@2.2.0
>         install: json@0.0.2
> $CWD/spm_modules/json/0.0.2/package.json
> true
>           found: json@0.0.2
>         install: underscore@1.6.0
> $CWD/spm_modules/underscore/1.6.0/package.json
> false
>         install: moment@2.6.0
>         install: handlebars-runtime@1.3.0
> $CWD/spm_modules/handlebars-runtime/1.3.0/package.json
> false
>         install: arale-base@1.2.0
> ```
>
